# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: default

stages:
  - stage: dev
    displayName: Deploy dev
    jobs:
      - job: DeployDev
        displayName: "Deploy dev"
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'GitHub'
            dockerComposeFile: '**/docker-compose-api.yaml'
            action: 'Run a Docker Compose command'