trigger: none

pool:
  name: default

stages:
  - stage: Dev
    jobs:
      - deployment: Deploy
        displayName: Deploy to Dev
        environment: Dev
        strategy:
          runOnce:
            deploy:              
              steps:
              - task: PowerShell@2
                displayName: Deploy api
                inputs:
                  targetType: 'inline'
                  script: 'docker-compose -f docker-compose-api.yaml -p local up -d'
              - task: SqlDacpacDeploymentOnMachineGroup@0
                displayName: Deploy database
                inputs:
                  TaskType: 'dacpac'
                  TargetMethod: 'connectionString'
                  ConnectionString: 'Server=localhost;Database=Database;User Id=sa;Password=yourStrong(!)Password;Encrypt=False'
  - stage: QA
    dependsOn: Dev
    jobs:
      - deployment: Deploy
        environment: QA
        strategy:
          runOnce:
            deploy:              
              steps:
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: 'docker-compose -f docker-compose-api.yaml -p local up -d'
  - stage: Prod
    dependsOn: QA
    jobs:
      - deployment: Deploy
        environment: Prod
        strategy:
          runOnce:
            deploy:              
              steps:
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: 'docker-compose -f docker-compose-api.yaml -p local up -d'