services:
  api: 
    restart: always
    image: api:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - C:\envs\local\images:/app/images
    environment:
      - Api__Url=http://localhost:80
      - Api__ImagesStoragePath=/app/images
      - Api__SqlServerConnectionString=Server=mssql;Database=Database;User Id=sa;Password=yourStrong(!)Password;Encrypt=False
    depends_on: 
      - mssql

  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - C:\envs\local\sqlserver\data:/var/opt/mssql/data
      - C:\envs\local\sqlserver\log:/var/opt/mssql/log
      - C:\envs\local\sqlserver\secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password