services:
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - C:\envs\local\sqlserver\data:/var/opt/mssql/data
      - C:\envs\local\sqlserver\log:/var/opt/mssql/log
      - C:\envs\local\sqlserver\secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password